@Todo.Api_HostAddress = https://localhost:7197

GET {{Todo.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

@id=1006
GET {{Todo.Api_HostAddress}}/api/todotasks/{id:int}

###

POST {{Todo.Api_HostAddress}}/api/todotasks
Content-Type: application/json

{

  "name": "data to add",
  "isComplete": 1
}


###
