@Todo.Api_HostAddress = https://localhost:7197


@id=1
GET {{Todo.Api_HostAddress}}/api/todotasks/{{id}}

###

POST {{Todo.Api_HostAddress}}/api/todotasks
Content-Type: application/json

{

  "name": "data to add",
  "isComplete": 1
}


###

GET {{Todo.Api_HostAddress}}/api/todotasks

###

@id=1

DELETE {{Todo.Api_HostAddress}}/api/todotasks/{{id}}

###
